addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo" % "0.9.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"       % "1.0.0")
addSbtPlugin("com.lucidchart"   % "sbt-scalafmt"  % "1.15")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"       % "1.1.2")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"  % "2.3")
addSbtPlugin("org.scoverage"    % "sbt-scoverage" % "1.5.1")
